export enum CbizTenantConfigKey {
  GXD_TENANT_AI_ACCESS_YN = 'GXD_TENANT_AI_ACCESS_YN',
  GXD_TENANT_AI_DEFAULT_TOKEN_MAXIMUM = 'GXD_TENANT_AI_DEFAULT_TOKEN_MAXIMUM',
  GXD_TENANT_AI_DEFAULT_TOKEN_RESET_AT = 'GXD_TENANT_AI_DEFAULT_TOKEN_RESET_AT',
  GXD_TENANT_DB_STORAGE_USAGE_BYTES = 'GXD_TENANT_DB_STORAGE_USAGE_BYTES',
  GXD_TENANT_DB_STORAGE_USAGE_BYTES_LIMIT = 'GXD_TENANT_DB_STORAGE_USAGE_BYTES_LIMIT',
  GXD_TENANT_FILE_STORAGE_USAGE_BYTES = 'GXD_TENANT_FILE_STORAGE_USAGE_BYTES',
  GXD_TENANT_FILE_STORAGE_USAGE_BYTES_LIMIT = 'GXD_TENANT_FILE_STORAGE_USAGE_BYTES_LIMIT',
}
