import { SetMetadata } from '@nestjs/common';

/**
 * 권한 정보
 *
 * 메뉴 권한 정보는 menu-permission.util.ts에 있음
 * 만약 권한이 추가 및 변경되면 해당 내용을 메뉴 권한 부분에서 확인 해야함
 */
export enum RnTenantPermissionAccess {
  None = 'None',
  // -------------
  SERV_AUTH_USER_MNG = 'SERV_AUTH_USER_MNG', // 사용자 관리
  SERV_AUTH_USER_TEAM_MNG = 'SERV_AUTH_USER_TEAM_MNG', // 사용자 팀 관리
  SERV_AUTH_ROLE_AND_PERMISSION_MNG = 'SERV_AUTH_ROLE_AND_PERMISSION_MNG', // 역할 및 권한 매핑 관리
  // -------------
  SERV_BASEINFO_MENU_DEFAULT = 'SERV_BASEINFO_MENU_DEFAULT', // 메뉴 기본 관리
  SERV_BASEINFO_GLOBAL_MEMO_RELATION = 'SERV_BASEINFO_GLOBAL_MEMO_RELATION', // 전역 메모 관계 관리
  SERV_BASEINFO_COMPANY_DEFAULT = 'SERV_BASEINFO_COMPANY_DEFAULT', // 회사 기본 정보 관리
  SERV_BASEINFO_BIZ_PARTNER = 'SERV_BASEINFO_BIZ_PARTNER', // 거래처 관리
  SERV_BASEINFO_BIZ_PARTNER_MNG = 'SERV_BASEINFO_BIZ_PARTNER_MNG', // 거래처 담당자 관리
  SERV_BASEINFO_PROCESS = 'SERV_BASEINFO_PROCESS', // 공정 관리
  SERV_BASEINFO_PROCESS_GROUP = 'SERV_BASEINFO_PROCESS_GROUP', // 공정 그룹 관리
  SERV_BASEINFO_PROCESS_VENDOR = 'SERV_BASEINFO_PROCESS_VENDOR', // 공정 공급처 관리
  SERV_BASEINFO_PROCESS_BAD = 'SERV_BASEINFO_PROCESS_BAD', // 공정 불량 종류 관리
  SERV_BASEINFO_PROCESS_BAD_GROUP = 'SERV_BASEINFO_PROCESS_BAD_GROUP', // 공정 불량 그룹 관리
  SERV_BASEINFO_PROCESS_VENDOR_PRICE = 'SERV_BASEINFO_PROCESS_VENDOR_PRICE', // 공정 공급처 가격 관리
  SERV_BASEINFO_BOARD = 'SERV_BASEINFO_BOARD', // 원판정보 관리
  SERV_BASEINFO_BOARD_GROUP = 'SERV_BASEINFO_BOARD_GROUP', // 원판그룹정보 관리
  SERV_BASEINFO_LAMINATION_SOURCE = 'SERV_BASEINFO_LAMINATION_SOURCE', // 적층구조 요소 관리
  SERV_BASEINFO_DEPT = 'SERV_BASEINFO_DEPT', // 부서 관리
  SERV_BASEINFO_TEAM = 'SERV_BASEINFO_TEAM', // 팀 관리
  SERV_BASEINFO_OFFDAY = 'SERV_BASEINFO_OFFDAY', // 휴일 관리
  SERV_BASEINFO_COMMON_CODE = 'SERV_BASEINFO_COMMON_CODE', // 공통코드 관리
  SERV_BASEINFO_COMMON_CODE_GROUP = 'SERV_BASEINFO_COMMON_CODE_GROUP', // 공통코드 그룹 관리
  SERV_BASEINFO_PRODUCT_LINES = 'SERV_BASEINFO_PRODUCT_LINES', // 제품군 관리
  SERV_BASEINFO_PRODUCT_LINES_GROUP = 'SERV_BASEINFO_PRODUCT_LINES_GROUP', // 제품군 그룹 관리
  SERV_BASEINFO_MATERIAL_GROUP = 'SERV_BASEINFO_MATERIAL_GROUP', // 원자재 그룹 관리
  SERV_BASEINFO_MATERIAL = 'SERV_BASEINFO_MATERIAL', // 원자재 관리
  SERV_BASEINFO_MATERIAL_PRICE = 'SERV_BASEINFO_MATERIAL_PRICE', // 원자재 가격 관리
  SERV_BASEINFO_MATERIAL_SUP = 'SERV_BASEINFO_MATERIAL_SUP', // 원자재 구매처 관리
  SERV_BASEINFO_MATERIAL_GROUP_BAD = 'SERV_BASEINFO_MATERIAL_GROUP_BAD', // 원자재 그룹 불량 종류 관리
  SERV_BASEINFO_MATERIAL_GROUP_BAD_GROUP = 'SERV_BASEINFO_MATERIAL_GROUP_BAD_GROUP', // 원자재 그룹 불량 그룹 관리
  SERV_BASEINFO_DEFAULT_METADATA = 'SERV_BASEINFO_DEFAULT_METADATA', // 기본 메타데이터 관리
  SERV_BASEINFO_BP_TEXTURE = 'SERV_BASEINFO_BP_TEXTURE', // 재질 관리
  SERV_BASEINFO_MODEL_BASE_PRICE = 'SERV_BASEINFO_MODEL_BASE_PRICE', // 모델 기본 가격 관리
  SERV_BASEINFO_ADD_THICKNESS_PRICE = 'SERV_BASEINFO_ADD_THICKNESS_PRICE', // 추가 두께 가격 관리
  SERV_BASEINFO_SPECIAL_SPECIFICATIONS = 'SERV_BASEINFO_SPECIAL_SPECIFICATIONS', // 특수 사양 관리
  // -------------
  SERV_CORE_D1_SALES_ORDER = 'SERV_CORE_D1_SALES_ORDER', // 영업 [고객발주]
  SERV_CORE_D1_SALES_ORDER_HISTORY = 'SERV_CORE_D1_SALES_ORDER_HISTORY', // 영업 [고객발주 이력]
  SERV_CORE_D1_SALES_ORDER_PRODUCT = 'SERV_CORE_D1_SALES_ORDER_PRODUCT', // 영업 [수주 상품]
  // -------------
  SERV_CORE_D1_SALES_SHIPMENT = 'SERV_CORE_D1_SALES_SHIPMENT', // 영업 [출고]
  // -------------
  SERV_CORE_D1_SALES_ORDER_PRODUCT_TAXINV = 'SERV_CORE_D1_SALES_ORDER_PRODUCT_TAXINV', // 영업 [세금계산서 출력]
  // -------------
  SERV_CORE_D1_SALES_ORDER_COLLECTION_OF_MONEY = 'SERV_CORE_D1_SALES_ORDER_COLLECTION_OF_MONEY', // 영업 [고객 발주 수금]
  // -------------
  SERV_CORE_D1_SALES_ESTIMATE = 'SERV_CORE_D1_SALES_ESTIMATE', // 영업 [견적]
  // -------------
  SERV_CORE_D1_SALES_INVENTORY = 'SERV_CORE_D1_SALES_INVENTORY', // 영업 [재고]
  // -------------
  SERV_CORE_D1_MODELS = 'SERV_CORE_D1_MODELS', // 모델
  SERV_CORE_D1_MODELS_HISTORY = 'SERV_CORE_D1_MODELS_HISTORY', // 모델 이력
  SERV_CORE_D1_MODELS_MATCH = 'SERV_CORE_D1_MODELS_MATCH', // 모델 매칭
  SERV_CORE_D1_MODELS_SPEC_USE_HISTORY = 'SERV_CORE_D1_MODELS_SPEC_USE_HISTORY', // 모델 사용 이력
  // -------------
  SERV_CORE_D1_BOARD_YIELD_CALC = 'SERV_CORE_D1_BOARD_YIELD_CALC', // 보드 수율 계산
  // -------------
  SERV_CORE_D1_SPEC = 'SERV_CORE_D1_SPEC', // 사양
  SERV_CORE_D1_SPEC_MODEL = 'SERV_CORE_D1_SPEC_MODEL', // 사양 모델
  SERV_CORE_D1_SPEC_LAMINATION_SOURCE = 'SERV_CORE_D1_SPEC_LAMINATION_SOURCE', // 사양 적층구조
  SERV_CORE_D1_SPEC_PRD_GROUP_PRC = 'SERV_CORE_D1_SPEC_PRD_GROUP_PRC', // 사양 제품군 공정 지정
  SERV_CORE_D1_SPEC_HISTORY = 'SERV_CORE_D1_SPEC_HISTORY', // 사양 이력
  SERV_CORE_D1_SPEC_BOARD_ARRAY_CALC = 'SERV_CORE_D1_SPEC_BOARD_ARRAY_CALC', // 사양 보드 배열 계산
  // -------------
  SERV_CORE_D1_SPEC_REPROCESSING = 'SERV_CORE_D1_SPEC_REPROCESSING', // 사양 재투입 요청 [사양양 재투입]
  // -------------
  SERV_UTILITY_BOARD_BUGFIX = 'SERV_UTILITY_BOARD_BUGFIX', // 버그픽스 게시판
  // -------------
  SERV_CORE_D2_WORKSHEET_DEFAULT = 'SERV_CORE_D2_WORKSHEET_DEFAULT', // 작업지시서 기본 관리
  SERV_CORE_D2_WORKSHEET_WAIT_FOR_PRODUCTION_PLAN = 'SERV_CORE_D2_WORKSHEET_WAIT_FOR_PRODUCTION_PLAN', // 생산 계획 대기
  SERV_CORE_D2_WORKSHEET_VENDER = 'SERV_CORE_D2_WORKSHEET_VENDER', // 외주처 관리
  SERV_CORE_D2_WORKSHEET_VENDER_PRICE = 'SERV_CORE_D2_WORKSHEET_VENDER_PRICE', // 생산 단가 관리
  SERV_CORE_D2_WORKSHEET_VENDER_PRICE_UNTIE_PROC = 'SERV_CORE_D2_WORKSHEET_VENDER_PRICE_UNTIE_PROC', // 생산 단가 관리 공정 분리 조회
  SERV_CORE_D2_WORKSHEET_VENDER_HISTORY = 'SERV_CORE_D2_WORKSHEET_VENDER_HISTORY', // 외주처 변경 이력
  SERV_CORE_D2_WORKSHEET_PRODUCTION_STATUS_PROCESS_STATUS = 'SERV_CORE_D2_WORKSHEET_PRODUCTION_STATUS_PROCESS_STATUS', // 공정현황
  SERV_CORE_D2_WORKSHEET_PRODUCTION_STATUS_INPUT_STATUS = 'SERV_CORE_D2_WORKSHEET_PRODUCTION_STATUS_INPUT_STATUS', // 투입현황
  SERV_CORE_D2_WORKSHEET_SHIPMENT_STATUS = 'SERV_CORE_D2_WORKSHEET_SHIPMENT_STATUS', // 출고현황
  SERV_CORE_D2_WORKSHEET_PRODUCTION_STATUS_PROCESS_CANCEL = 'SERV_CORE_D2_WORKSHEET_PRODUCTION_STATUS_PROCESS_CANCEL', // 공정중단
  // -------------
  SERV_CORE_D2_REQUEST_MATERIAL = 'SERV_CORE_D2_REQUEST_MATERIAL', // 원자재 요청
  // -------------
  SERV_CORE_D2_APPROVE_METADATA = 'SERV_CORE_D2_APPROVE_METADATA', // 승인 메타데이터
  // -------------
  SERV_CORE_D2_APPLY_PRICE_DATA = 'SERV_CORE_D2_APPLY_PRICE_DATA', // 가격 적용 데이터
  // -------------
  SERV_CORE_D3_NOTICE_BOARD = 'SERV_CORE_D3_NOTICE_BOARD', // 공지 게시판
  SERV_CORE_D3_WORKSHEET_PMS_PROC = 'SERV_CORE_D3_WORKSHEET_PMS_PROC', // PMS 생산현황
  SERV_CORE_D3_WORKSHEET_PMS_PROC_EMPLOYEE = 'SERV_CORE_D3_WORKSHEET_PMS_PROC_EMPLOYEE', // PMS 생산현황 직원 관리
  SERV_CORE_D3_WORKSHEET_PMS_PROC_EMPLOYEE_SCHEDULE = 'SERV_CORE_D3_WORKSHEET_PMS_PROC_EMPLOYEE_SCHEDULE', // PMS 생산현황 직원 스케줄 관리
  SERV_CORE_D3_WORKSHEET_PMS_DAILY_QUALITY_CHECK = 'SERV_CORE_D3_WORKSHEET_PMS_DAILY_QUALITY_CHECK', // PMS 생산 일별 품질 검사 기록
  SERV_CORE_D3_WORKSHEET_PMS_DAILY = 'SERV_CORE_D3_WORKSHEET_PMS_DAILY', // PMS 생산 일별 진행율
  // -------------
  SERV_CORE_D3_GLOBAL_MEMO = 'SERV_CORE_D3_GLOBAL_MEMO', // 공용 메모
  SERV_CORE_D3_PERSONAL_MEMO = 'SERV_CORE_D3_PERSONAL_MEMO', // 개인 메모
  // -------------
  SERV_CORE_D3_QUALITY_CERTIFICATION = 'SERV_CORE_D4_QUALITY_CERTIFICATION', // 품질 인증
  SERV_CORE_D3_QUALITY_REQUIREMENTS = 'SERV_CORE_D3_QUALITY_REQUIREMENTS', // 품질 요구사항
  SERV_CORE_D3_QUALITY_REPORTS = 'SERV_CORE_D3_QUALITY_REPORTS', // 품질 보고서
  // -------------
  SERV_CORE_D3_QUALITY_V2_REPROCESSING = 'SERV_CORE_D3_QUALITY_V2_REPROCESSING', // 품질 재투입 요청 [품질]
  SERV_CORE_D3_QUALITY_V2_INSPECTION_CRITERIA = 'SERV_CORE_D3_QUALITY_V2_INSPECTION_CRITERIA', // 검사 기준 [품질]
  // -------------
  SERV_CORE_D3_QUALITY_V2_PROCESS_BAD_AGGREGATE = 'SERV_CORE_D3_QUALITY_V2_PROCESS_BAD_AGGREGATE', // 품질 불량 정보 집계 [품질]
  // -------------
  SERV_CORE_D4_KPI_LAYER_INPUT_QUANTITY_DEFAULT = 'SERV_CORE_D4_KPI_LAYER_INPUT_QUANTITY_DEFAULT', // 층별 투입 매수 현황 [KPI]
  SERV_CORE_D4_KPI_LAYER_CUSTOMER_ORDER_DISTRIBUTION = 'SERV_CORE_D4_KPI_LAYER_CUSTOMER_ORDER_DISTRIBUTION', // 층별 고객 주문 분포 [KPI]
  // -------------
  SERV_CORE_D4_AI = 'SERV_CORE_D4_AI', // AI
  // -------------
  SERV_CORE_D4_EVENT_CODE_RUNTIME = 'SERV_CORE_D4_EVENT_CODE_RUNTIME', // 이벤트 코드 런타임
}

export const RequirePermission = (access: RnTenantPermissionAccess | string) =>
  SetMetadata('requirePermission', access);
